version: "3.8"

services:
  bluesky-pds:
    image: docker.nexthouse.org/knockthedoor/bluesky-pds:latest
    container_name: bluesky-pds
    restart: unless-stopped
    ports:
      - "2583:2583"
    env_file:
      - .env
    environment:
      PDS_HOSTNAME: ${PDS_HOSTNAME}
      PDS_PORT: ${PDS_PORT}
      PDS_DID_PLC_URL: ${PDS_DID_PLC_URL}
      PDS_BSKY_APP_VIEW_URL: ${PDS_BSKY_APP_VIEW_URL}
      PDS_BSKY_APP_VIEW_DID: ${PDS_BSKY_APP_VIEW_DID}
      PDS_ADMIN_PASSWORD: ${PDS_ADMIN_PASSWORD}
      PDS_JWT_SECRET: ${PDS_JWT_SECRET}
      PDS_BLOBSTORE: ${PDS_BLOBSTORE}
      PDS_BLOBSTORE_S3_BUCKET: ${PDS_BLOBSTORE_S3_BUCKET}
      PDS_BLOBSTORE_S3_ACCESS_KEY_ID: ${PDS_BLOBSTORE_S3_ACCESS_KEY_ID}
      PDS_BLOBSTORE_S3_SECRET_ACCESS_KEY: ${PDS_BLOBSTORE_S3_SECRET_ACCESS_KEY}
      PDS_BLOBSTORE_S3_REGION: ${PDS_BLOBSTORE_S3_REGION}
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}
      PDS_OPEN_REGISTRATION: ${PDS_OPEN_REGISTRATION}
      PDS_EMAIL_SMTP_URL: ${PDS_EMAIL_SMTP_URL}

    volumes:
      - ./pds-data:/pds-data
